name: SaveSpot
version: '1.0-SNAPSHOT'
main: polatrk.saveSpot.SaveSpot
api-version: '1.19'
commands:
  spot:
    description: "Usage: /spot <remove | cancel | save | goto | show> <private | public> <name>"
    usage: /spot